theme: jekyll-theme-dinky

google_analytics: UA-15566807-1
google_verification: 9ht805RwYCWV-TOp0OgBYluGH9--CzPwHdkTEVGi-lg

title: Eli White
description: Geek. Father. Husband. Gamer. Developer. Business Owner.
